name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.3.47
  google_fonts: ^5.0.0

  random_color: ^1.0.5



  intl: ^0.19.0
  http: ^1.2.2

  url_launcher: ^6.1.9
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bilimsever-usman-aga.jpg
    - assets/softtech-photo.png
